---
sudo: required

language: python

addons:
  apt:
    packages:
      - git

before_install:
  - scripts/travis.sh

install:
  - pip install -r requirements.txt

env:
  global:
    - OSISM_VERSION=latest
  matrix:
    - OPENSTACK_VERSION=pike
    - OPENSTACK_VERSION=queens

script:
  - bash scripts/build.sh

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/push.sh; fi'

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
