#!/usr/bin/env bash
set -x

PROJECT=kolla-ansible

# Available environment variables
#
# OPENSTACK_VERSION
# OSISM_VERSION
# PUSH_COMMIT
# REPOSITORY

# Set default values

OPENSTACK_VERSION=${OPENSTACK_VERSION:-pike}
OSISM_VERSION=${OSISM_VERSION:-latest}
PUSH_COMMIT=${PUSH_COMMIT:-false}
REPOSITORY=${REPOSITORY:-osism/$PROJECT}

COMMIT=$(git rev-parse --short HEAD)

if [[ $OSISM_VERSION == "latest" ]]; then
    OSISM_VERSION=$(basename $(readlink release/latest))
    docker tag "$REPOSITORY:$OPENSTACK_VERSION-latest-$COMMIT" "$REPOSITORY:$OPENSTACK_VERSION-$OSISM_VERSION-$COMMIT"
fi

TAG=$REPOSITORY:$OPENSTACK_VERSION-$OSISM_VERSION

if [[ $PUSH_COMMIT == "true" ]]; then
    docker push "$REPOSITORY:$OSISM_VERSION-$COMMIT"
fi

docker tag "$REPOSITORY:$OPENSTACK_VERSION-$OSISM_VERSION-$COMMIT" "$REPOSITORY:$OPENSTACK_VERSION-$OSISM_VERSION"
docker push "$REPOSITORY:$OPENSTACK_VERSION-$OSISM_VERSION"
